# Copyright Brandon B. Jozsa/JinkIT and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

release_group: null

labels:
  controller:
    node_selector_key: control-plane
    node_selector_value: enabled
  speaker:
    node_selector_key: control-plane
    node_selector_value: enabled

pod:
  dns_policy: Default
  replicas:
    metallb_controller: 2
    test_bgp_router: 1
  lifecycle:
    metallb:
      upgrades:
        deployments:
          revision_history: 5
          pod_replacement_strategy: RollingUpdate
          rolling_update:
            max_unavailable: 1
            max_surge: 1
        daemonsets:
          pod_replacement_strategy: RollingUpdate
          infra_metallb:
            enabled: true
            min_ready_seconds: 0
            max_unavailable: 1
      disruption_budget:
        kube_controller_manager:
          min_available: 1
      termination_grace_period:
        kube_controller_manager:
          timeout: 30
  resources:
    enabled: true
    metallb:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "1024Mi"
        cpu: "2000m"
  tolerations:
    infra_metallb:
      enabled: true
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists

containers:
  controller:
    image: metallb/controller:v0.7.3
    pull_policy: "IfNotPresent"
  speaker:
    image: metallb/speaker:v0.7.3
    pull_policy: "IfNotPresent"
  test_bgp_router:
    image: metallb/test-bgp-router:v0.7.3
    pull_policy: "IfNotPresent"

args:
  infra_metallb:
    port: 7472
    config: metallb-config-l2

watcher_sa:
  subjects:
    c_name: controller
    s_name: speaker

conf:
  metallb_cm_l2: |
    address-pools:
    - name: default
      protocol: layer2
      avoid-buggy-ips: true
      addresses:
      - 192.168.3.240-192.168.3.250
  metallb_cm_l3: |
    peers:
    - peer-address: 192.168.1.1
      peer-asn: 64512
      my-asn: 64512
    address-pools:
    - name: default
      protocol: bgp
      avoid-buggy-ips: true
      addresses:
      - 192.168.1.224/27
  metallb_test_bgp_test_config: |
    peers:
    - my-asn: 64512
      peer-asn: 64512
      peer-address: 10.96.0.103
    - my-asn: 64512
      peer-asn: 64512
      peer-address: 10.96.0.104
    address-pools:
    - name: default
      protocol: bgp
      avoid-buggy-ips: true
      addresses:
      - 192.168.1.224/27

services:
  test_bgp_router_ui:
    name: test-bgp-router-ui
    type: NodePort
    labels:
      application: test-bgp-router
      component: loadbalancer
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  test_bgp_router_quagga:
    name: test-bgp-router-quagga
    type: ClusterIP
    cluster_ip: 10.96.0.104
    labels:
      application: test-bgp-router
      component: loadbalancer
    ports:
    - name: bgp
      port: 179
      protocol: TCP
      targetPort: quagga
  test_bgp_router_bird:
    name: test-bgp-router-bird
    type: ClusterIP
    cluster_ip: 10.96.0.103
    labels:
      application: test-bgp-router
      component: loadbalancer
    ports:
    - name: bgp
      port: 179
      protocol: TCP
      targetPort: bird

security:
  rbac:
    controller:
      - apigroups:
          - ""
        resources:
          - services
        verbs:
          - get
          - list
          - watch
          - update
      - apigroups:
          - ""
        resources:
          - services/status
        verbs:
          - update
      - apigroups:
          - ""
        resources:
          - events
        verbs:
          - create
          - patch
    speaker:
      - apigroups:
          - ""
        resources:
          - services
          - endpoints
          - nodes
        verbs:
          - get
          - list
          - watch
    watcher:
      - apigroups:
          - ""
        resources:
          - events
        verbs:
          - create
      - apigroups:
          - ""
        resources:
          - configmaps
        verbs:
          - get
          - list
          - watch
  pods:
    metallb_controller:
      security_context:
        enabled: true
        runAsNonRoot: true
        runAsUser: 65534
  containers:
    test_bgp_router:
      security_context:
        capabilities:
          add:
          - net_admin
          - sys_admin
    metallb_controller:
      security_context:
        enabled: true
        allowPrivilegeEscalation: false
        capabilities:
          drop:
          - all
        readOnlyRootFilesystem: true
    metallb_speaker:
      security_context:
        enabled: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
            - all
          add:
            - net_raw

manifests:
  configmap_metallb_l2: true
  configmap_metallb_l3: true
  metallb_controller_deployment: true
  metallb_speaker_daemonSet: true
  test_service_bgprouterbird: true
  test_service_bgprouterquagga: true
  test_service_bgprouterui: true
  test_deployment_nginx: true
  test_bgp_router: false
  test_bgp_router_configmap: false
