apiVersion: v1
entries:
  grafana:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/grafana/helm-charts
        - name: Upstream Project
          url: https://github.com/grafana/grafana
    apiVersion: v2
    appVersion: 12.0.2
    created: "2026-05-10T03:13:54.531201441Z"
    description: Custom grafana-srsran chart packaged by Brandon B. Jozsa
    digest: 847cbf8e07e3230f3f75d0c37456001914daeed405d33a44bd1491ef0f6afc4e
    home: https://grafana.com
    icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
    keywords:
    - monitoring
    - metric
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: github@jkroepke.de
      name: jkroepke
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    - https://github.com/grafana/helm-charts
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-grafana/grafana-9.2.10.tgz
    version: 9.2.10
  grafana-deployment:
  - apiVersion: v2
    appVersion: 9.2.10
    created: "2026-05-10T03:13:54.534851888Z"
    dependencies:
    - alias: grafana
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 9.2.10
    - alias: telegraf
      name: telegraf
      repository: https://helm.influxdata.com/
      version: 1.8.60
    - alias: influxdb3
      name: influxdb3
      repository: https://srsran.github.io/srsRAN_Project_helm/
      version: 1.0.0
    description: Custom grafana-srsran chart packaged by Brandon B. Jozsa
    digest: 1059cb6d219c94f18bf195c718e508cb4c97dbb06c00c663f80ba1e99d40ea48
    name: grafana-deployment
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-grafana-srsran/grafana-deployment-1.3.0.tgz
    version: 1.3.0
  influxdb3:
  - apiVersion: v2
    appVersion: 3.1.0-core
    created: "2026-05-10T03:13:54.535066261Z"
    description: Custom srsran-influxdb chart packaged by Brandon B. Jozsa
    digest: 5457b550d02a581927451bf84b88854f6c18ba1fdd548c8ecf08aa08bd115336
    name: influxdb3
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-influxdb3/influxdb3-1.0.0.tgz
    version: 1.0.0
  kubevirt-redfish:
  - apiVersion: v2
    appVersion: v0.2.3-f87ff92
    created: "2026-05-10T03:13:54.527599083Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 2ab7306494a8d1998253cef83788eb50a6fe9d58d7a8c389dfa72d06bc4294ad
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v0.2.2-fee285c
    created: "2026-05-10T03:13:54.526891796Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: f92a679f2429e94df4a1ab8297bc3d749a3f08d365d78d4eb158d032dbdf33ea
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v0.2.1-fee285c1
    created: "2026-05-10T03:13:54.52608557Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 1fa72f48e13575ed80c5c13f1f4f1f2ff71721d1594a76427ddf83ec9a9fe6ee
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-fee285c1.tgz
    version: 0.2.1-fee285c1
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2026-05-10T03:13:54.525411614Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: a243ba0c35b589e0a20e2919b2dab65cf139fe84914de110d6e90817200342bf
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-73abb30.tgz
    version: 0.2.1-73abb30
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2026-05-10T03:13:54.524656865Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: 0e736215a0a05dafd5702e6093400c2d0050174d69477d5b664d048ee79de925
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.0.0-0.2.0-f310b659.tgz
    version: 0.0.0-0.2.0-f310b659
  linuxptp:
  - apiVersion: v2
    appVersion: 4.4.0
    created: "2026-05-10T03:13:54.535532284Z"
    description: Custom srsran-ptp chart packaged by Brandon B. Jozsa
    digest: 758d5edf35923b7c8f1ecf2b9bbb23b0dc17f0f4e27cf66493ea29a5feb0533e
    home: https://linuxptp.nwtime.org/
    icon: https://linuxptp.nwtime.org/images/logo.png
    keywords:
    - linuxptp
    - ptp4l
    - phc2sys
    - ptp
    - srsran
    kubeVersion: '>= 1.24.0-0'
    name: linuxptp
    sources:
    - https://github.com/richardcochran/linuxptp
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-linuxptp/linuxptp-1.3.1.tgz
    version: 1.3.1
  metrics-server:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2026-05-10T03:13:54.535738315Z"
    description: Custom srsran-metrics-server chart packaged by Brandon B. Jozsa
    digest: 01ebbd80897ada4331a9750df735690ee981c7b6e6195abbc673ae350c36dd0f
    name: metrics-server
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-metrics-server/metrics-server-1.2.0.tgz
    version: 1.2.0
  ocp-on-cnv:
  - apiVersion: v2
    appVersion: v0.1.1-ac971ff
    created: "2026-05-10T03:13:54.528440122Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: e1112c1536f7715abf10fb40b2feecff7416d9108d9d8390e377bc897a08bd1b
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: "1.0"
    created: "2026-05-10T03:13:54.528159418Z"
    description: This helm chart can be used to deploy OpenShift on top of OpenShift
      Virtualization using OpenShift's BMO and Fakefish.
    digest: aef476a611be690d3e86a45532ace9bd57fca4981cc0ee20df300efcfb5d65e8
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: v0.1.0-ac971ff
    created: "2026-05-10T03:13:54.527877323Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 7943b24d547a92c0209cda5293ed98a3d9aaadb26dc569003a01feba65527a45
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0-devel.tgz
    version: 0.1.0-devel
  onap-smo-lite:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-05-10T03:13:54.536704201Z"
    description: Custom srsran onap-smo-lite chart packaged by Brandon B. Jozsa
    digest: 540dd490214a49feca03e9057fc9f700b76935b7dce1b114dab5b92cd8f217ac
    name: onap-smo-lite
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-onap-smo-lite/onap-smo-lite-0.3.0.tgz
    version: 0.3.0
  rt-tests:
  - apiVersion: v2
    appVersion: "2.8"
    created: "2026-05-10T03:13:54.537721035Z"
    description: Custom srsran-test chart packaged by Brandon B. Jozsa
    digest: 4b1f7fdef908c80047215c4e1dc00a51cc279961b32dc09b5c2de97ea712c221
    home: https://wiki.linuxfoundation.org/realtime/documentation/howto/tools/rt-tests
    icon: https://wiki.linuxfoundation.org/_media/wiki/logo.png
    keywords:
    - rt-tests
    - srsran
    kubeVersion: '>= 1.16.0-0'
    name: rt-tests
    sources:
    - https://web.git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-rt-tests/rt-tests-1.0.0.tgz
    version: 1.0.0
  ru-emulator:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2026-05-10T03:13:54.538321932Z"
    description: Custom srsran-emulator chart packaged by Brandon B. Jozsa
    digest: 0971454b97ee5649df63e02f3d795022844ee3bb5e3b5422f2fe0db79cc86240
    name: ru-emulator
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-ru-emulator/ru-emulator-1.1.0.tgz
    version: 1.1.0
  srsran-cu-du:
  - apiVersion: v2
    appVersion: "25.04"
    created: "2026-05-10T03:13:54.537430056Z"
    description: Custom srsran-project chart packaged by Brandon B. Jozsa
    digest: e9ef5fbb76759522700462e04adbde8cd3f00b012693cae347e4ab69cf11ecca
    home: https://docs.srsran.com/projects/project/en/latest/
    icon: https://docs.srsran.com/en/latest/_static/logo.png
    keywords:
    - srsran
    - 5g
    - oran
    - vran
    - gnb
    - mobile
    kubeVersion: '>= 1.24.0-0'
    name: srsran-cu-du
    sources:
    - https://github.com/srsran/srsran_project
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-project/srsran-cu-du-2.3.1.tgz
    version: 2.3.1
  tuned:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-05-10T03:13:54.538843498Z"
    description: Custom srsran-tuned chart packaged by Brandon B. Jozsa
    digest: 75a74147da2233cf58e25c2ec4336a572baf41e064b08e6051f1ea2a86d8bce3
    name: tuned
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-tuned/tuned-0.5.0.tgz
    version: 0.5.0
  vms-on-ocpv:
  - apiVersion: v2
    appVersion: v0.1.1-ff18cb3
    created: "2026-05-10T03:13:54.539314659Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: c730d50352d78a9b7878d12d7631300368729c8449b31461103e8fb970fb0d2b
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v0.1.0-ff18cb3
    created: "2026-05-10T03:13:54.539090961Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: ffa58bbbb5c0bed7cc7d92337035c1f0bdeb6d5d8a9e3cdfa9207edd44609bf2
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.0.tgz
    version: 0.1.0
generated: "2026-05-10T03:13:54.523123557Z"
