apiVersion: v1
entries:
  grafana:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/links: |
        - name: Chart Source
          url: https://github.com/grafana/helm-charts
        - name: Upstream Project
          url: https://github.com/grafana/grafana
    apiVersion: v2
    appVersion: 12.0.2
    created: "2026-05-31T03:16:32.992255058Z"
    description: Custom grafana-srsran chart packaged by Brandon B. Jozsa
    digest: 540b5a12f56ea305f9d972a20a1a5051326f3a6a0da1c4155db27bda923feb82
    home: https://grafana.com
    icon: https://artifacthub.io/image/b4fed1a7-6c8f-4945-b99d-096efa3e4116
    keywords:
    - monitoring
    - metric
    kubeVersion: ^1.8.0-0
    maintainers:
    - email: zanhsieh@gmail.com
      name: zanhsieh
    - email: rluckie@cisco.com
      name: rtluckie
    - email: maor.friedman@redhat.com
      name: maorfr
    - email: miroslav.hadzhiev@gmail.com
      name: Xtigyro
    - email: mail@torstenwalter.de
      name: torstenwalter
    - email: github@jkroepke.de
      name: jkroepke
    name: grafana
    sources:
    - https://github.com/grafana/grafana
    - https://github.com/grafana/helm-charts
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-grafana/grafana-9.2.10.tgz
    version: 9.2.10
  grafana-deployment:
  - apiVersion: v2
    appVersion: 9.2.10
    created: "2026-05-31T03:16:32.997352983Z"
    dependencies:
    - alias: grafana
      name: grafana
      repository: https://grafana.github.io/helm-charts
      version: 9.2.10
    - alias: telegraf
      name: telegraf
      repository: https://helm.influxdata.com/
      version: 1.8.60
    - alias: influxdb3
      name: influxdb3
      repository: https://srsran.github.io/srsRAN_Project_helm/
      version: 1.0.0
    description: Custom grafana-srsran chart packaged by Brandon B. Jozsa
    digest: 7c2617486bc455e446cb09626f12a6987be7e51da4eeba28b404e29da152b789
    name: grafana-deployment
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-grafana-srsran/grafana-deployment-1.3.0.tgz
    version: 1.3.0
  influxdb3:
  - apiVersion: v2
    appVersion: 3.1.0-core
    created: "2026-05-31T03:16:32.997647912Z"
    description: Custom srsran-influxdb chart packaged by Brandon B. Jozsa
    digest: 863ddcb1487faeaf9e03635ad4a26e1d54ff224017b1e1aa4f07b27a344256a9
    name: influxdb3
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-influxdb3/influxdb3-1.0.0.tgz
    version: 1.0.0
  kubevirt-redfish:
  - apiVersion: v2
    appVersion: v0.2.3-f87ff92
    created: "2026-05-31T03:16:32.988091596Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: d16f38cd1b3092e52850120c5172c39eb91570e64b6727fa1e8377711cbeb834
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v0.2.2-fee285c
    created: "2026-05-31T03:16:32.987220672Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: f92a679f2429e94df4a1ab8297bc3d749a3f08d365d78d4eb158d032dbdf33ea
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v0.2.1-fee285c1
    created: "2026-05-31T03:16:32.986288975Z"
    description: Custom kubevirt-redfish chart with enhanced features
    digest: 1fa72f48e13575ed80c5c13f1f4f1f2ff71721d1594a76427ddf83ec9a9fe6ee
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-fee285c1.tgz
    version: 0.2.1-fee285c1
  - apiVersion: v2
    appVersion: v0.2.1
    created: "2026-05-31T03:16:32.984445353Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: a243ba0c35b589e0a20e2919b2dab65cf139fe84914de110d6e90817200342bf
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.2.1-73abb30.tgz
    version: 0.2.1-73abb30
  - apiVersion: v2
    appVersion: v0.2.0
    created: "2026-05-31T03:16:32.98356983Z"
    description: A Helm chart that provides a Redfish API server for KubeVirt VMs
    digest: 0e736215a0a05dafd5702e6093400c2d0050174d69477d5b664d048ee79de925
    home: https://github.com/kubevirt/kubevirt-redfish
    icon: https://raw.githubusercontent.com/kubevirt/kubevirt/main/logo/kubevirt-logo.png
    keywords:
    - kubevirt
    - redfish
    - virtualization
    - api
    maintainers:
    - email: bjozsa@redhat.com
      name: Brandon B. Jozsa
    name: kubevirt-redfish
    sources:
    - https://github.com/kubevirt/kubevirt-redfish
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/kubevirt-redfish/kubevirt-redfish-0.0.0-0.2.0-f310b659.tgz
    version: 0.0.0-0.2.0-f310b659
  linuxptp:
  - apiVersion: v2
    appVersion: 4.4.0
    created: "2026-05-31T03:16:32.998214258Z"
    description: Custom srsran-ptp chart packaged by Brandon B. Jozsa
    digest: 0b918158a535bd2cd76ce378d6bb791e185f6b78302a5b850effcbb30f663697
    home: https://linuxptp.nwtime.org/
    icon: https://linuxptp.nwtime.org/images/logo.png
    keywords:
    - linuxptp
    - ptp4l
    - phc2sys
    - ptp
    - srsran
    kubeVersion: '>= 1.24.0-0'
    name: linuxptp
    sources:
    - https://github.com/richardcochran/linuxptp
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-linuxptp/linuxptp-1.3.1.tgz
    version: 1.3.1
  metrics-server:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2026-05-31T03:16:32.998478591Z"
    description: Custom srsran-metrics-server chart packaged by Brandon B. Jozsa
    digest: ac9ed895fa54760f90e3c27cede924a69834e79ed432ea27bb45631792026550
    name: metrics-server
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-metrics-server/metrics-server-1.2.0.tgz
    version: 1.2.0
  ocp-on-cnv:
  - apiVersion: v2
    appVersion: v0.1.1-ac971ff
    created: "2026-05-31T03:16:32.989346055Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: d63b04e9441691288c43220af573b9ca5444e553d04aff6e68c14e372c5d8150
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: "1.0"
    created: "2026-05-31T03:16:32.988980383Z"
    description: This helm chart can be used to deploy OpenShift on top of OpenShift
      Virtualization using OpenShift's BMO and Fakefish.
    digest: aef476a611be690d3e86a45532ace9bd57fca4981cc0ee20df300efcfb5d65e8
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v2
    appVersion: v0.1.0-ac971ff
    created: "2026-05-31T03:16:32.988468389Z"
    description: 'Deprecated: VMs w/Fakefish for ZTP testing'
    digest: 7943b24d547a92c0209cda5293ed98a3d9aaadb26dc569003a01feba65527a45
    name: ocp-on-cnv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/ocp-on-cnv/ocp-on-cnv-0.1.0-devel.tgz
    version: 0.1.0-devel
  onap-smo-lite:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-05-31T03:16:32.999667418Z"
    description: Custom srsran onap-smo-lite chart packaged by Brandon B. Jozsa
    digest: 0f60963326235e862db51a609a2ced52643c9b3a1173b153dc60871d6807b5c1
    name: onap-smo-lite
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-onap-smo-lite/onap-smo-lite-0.3.0.tgz
    version: 0.3.0
  rt-tests:
  - apiVersion: v2
    appVersion: "2.8"
    created: "2026-05-31T03:16:33.000656011Z"
    description: Custom srsran-test chart packaged by Brandon B. Jozsa
    digest: 92d2dfa8cec2e43db30556be53c20ee7a1f050f9cd744b6c49f660279d2fae84
    home: https://wiki.linuxfoundation.org/realtime/documentation/howto/tools/rt-tests
    icon: https://wiki.linuxfoundation.org/_media/wiki/logo.png
    keywords:
    - rt-tests
    - srsran
    kubeVersion: '>= 1.16.0-0'
    name: rt-tests
    sources:
    - https://web.git.kernel.org/pub/scm/utils/rt-tests/rt-tests.git/
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-rt-tests/rt-tests-1.0.0.tgz
    version: 1.0.0
  ru-emulator:
  - apiVersion: v2
    appVersion: 2024.10.0
    created: "2026-05-31T03:16:33.000978442Z"
    description: Custom srsran-emulator chart packaged by Brandon B. Jozsa
    digest: ab1c48d1b0eb7efa12f26531b6f432d6473078c6ffaf07decaf50d16a453f128
    name: ru-emulator
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-ru-emulator/ru-emulator-1.1.0.tgz
    version: 1.1.0
  srsran-cu-du:
  - apiVersion: v2
    appVersion: "25.04"
    created: "2026-05-31T03:16:33.000347436Z"
    description: Custom srsran-project chart packaged by Brandon B. Jozsa
    digest: 61877ddef05ee867b1b29b6d79442f672173ebeba4b3330cbdc0c6a732096d1b
    home: https://docs.srsran.com/projects/project/en/latest/
    icon: https://docs.srsran.com/en/latest/_static/logo.png
    keywords:
    - srsran
    - 5g
    - oran
    - vran
    - gnb
    - mobile
    kubeVersion: '>= 1.24.0-0'
    name: srsran-cu-du
    sources:
    - https://github.com/srsran/srsran_project
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-project/srsran-cu-du-2.3.1.tgz
    version: 2.3.1
  tuned:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-05-31T03:16:33.001276517Z"
    description: Custom srsran-tuned chart packaged by Brandon B. Jozsa
    digest: a9e73298c9180bcf5a83c91123b8a36045aedab6d1dba9faed7fe8eee20cf606
    name: tuned
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/srsran-tuned/tuned-0.5.0.tgz
    version: 0.5.0
  vms-on-ocpv:
  - apiVersion: v2
    appVersion: v0.1.1-ff18cb3
    created: "2026-05-31T03:16:33.00198603Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: 3d8d99d2c49145daea33e7b0b724aadb4bd7aca4d414e61cc7427fc5ad8fc5a7
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v0.1.0-ff18cb3
    created: "2026-05-31T03:16:33.001642179Z"
    description: Simple OpenShift Virtualization chart, typically used for kubevirt-redfish
      testing
    digest: ffa58bbbb5c0bed7cc7d92337035c1f0bdeb6d5d8a9e3cdfa9207edd44609bf2
    home: https://github.com/v1k0d3n/vms-on-ocpv
    keywords:
    - kubevirt
    - virtualization
    - vm
    - openshift
    maintainers:
    - email: v1k0d3n@example.com
      name: v1k0d3n
    name: vms-on-ocpv
    sources:
    - https://github.com/v1k0d3n/vms-on-ocpv
    type: application
    urls:
    - https://v1k0d3n.github.io/charts/vms-on-ocpv/vms-on-ocpv-0.1.0.tgz
    version: 0.1.0
generated: "2026-05-31T03:16:32.982388027Z"
